version: '3'

env:
  GOPATH:
    sh: go env GOPATH
  TZ: UTC
  PARALLEL: 4

tasks:
  install:
    deps:
      - lint:install
      - test:install

  lint:install:
    status:
      - test -f $GOPATH/bin/golangci-lint
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
  lint:
    deps:
      - lint:install
      - mocks
    cmds:
      - golangci-lint run

  test:install:
    status:
      - go version
      - test -f $GOPATH/bin/gotestsum
    cmds:
      - go install gotest.tools/gotestsum@latest
  test:
    deps:
      - test:install
      - mocks
    cmds:
      - gotestsum --junitfile=unit-tests.xml -- -timeout 30s -race -parallel $PARALLEL -count=1 ./...

  mocks:install:
    status:
      - test -f $GOPATH/bin/mockery
    cmds:
      - go install github.com/vektra/mockery/v2@v2.42.0

  mocks:
    deps:
      - mocks:install
    cmds:
      - mockery

  ci:
    cmds:
      - task: lint
      - task: test

