name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - '**'

jobs:
  ci:
    name: Continuous integration
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.0'
          check-latest: true
          cache-dependency-path: go.sum
      - name: Run tests
        run: go test ./... -v -count=1

